### ISSUE TITLE
Postfix (or Prefix) Existential Operator

### ISSUE THREAD

**Issue by Jamesernator** [claudepache/es-optional-chaining#13]
Similar to #10 I'd like to suggest a unary (whether prefix or postfix) operator for checking if an expression is undefined/null based on [CoffeeScript's existential operator](http://coffeescript.org/#existential-operator).

I'd imagine it having the same symbol as in #10.

Example of syntax:

```js
// postfix form
if (user??) {
    // do action for user
} else {
    // user is anonymous do action for anonymous users
}

// prefix form
if (??user) {
    // do action for user
} else {
    // user is anonymous do action for anonymous users
}
```

While this idea is essentially a short form for `== null` I feel it gives more indication of intent than explicitly using the weak typing of undefined/null.

**Comment by RangerMauve** [comment]
How is this better than just using the existing mechanics for "truthy-ness"? The only benefit is it won't convert `0` and `''` to `false`.

**Comment by claudepache** [comment]
I don’t think that `if (foo??)` is really clearer than `if (foo != null)`. At least for me, it is _less_ readable, because I am accustomed to the `!= null` form.

It is true, however, that the form `foo != null` may not be well understood by casual users, leading to potential confusions. But well; I think it is better for them to learn such an idiomatic form that they will encounter anyway, than to add yet another syntax for everyone.

Also, the proposed semantics is quite different from the null-coalescing operator `??`. That is to say, I am unable to guess what you mean by `foo??` just knowing what `foo??bar` means. So, in case we really want to add something like that, let’s just write `if (foo?)` like CoffeeScript.

**Comment by claudepache** [comment]
Thanks for you suggestion. Because its value is not clear to me, and because I want to restrict the scope of the current proposal, I won’t include it in my work.

If you think that `if (user != null)` deserves a better syntax, please make your case on the es-discuss mailing list.
