### ISSUE TITLE
Do you have a babel plugin?

### ISSUE THREAD

**Issue by a-x-** [claudepache/es-optional-chaining#6]
... and what the possibilities for standardization?

**Comment by a-x-** [comment]
I glad to find your proposal because I started thinking of the same a few months ago
https://twitter.com/mxtnr/status/716277270080536576

**Comment by claudepache** [comment]
No I don’t have Babel plugin. If someone volunteers to write one, I would be happy.

**Comment by nhz-io** [comment]
I'll take it on

**Comment by claudepache** [comment]
Regarding standardisation, there is currently nobody from TC39 that wanted to be champion, and these last weeks I have not worked on it. But please, ask one question by issue.

**Comment by claudepache** [comment]
@nhz-io Thanks. If it helps, I can write the expansion of `a?.b`, etc., in pseudo-JavaScript code with examples.

**Comment by nhz-io** [comment]
Yep, it will be great, also pick a name too, i am not good with names, and maybe even make a repo and add me as collaborator. I will get to it this weekend (Too busy at work to take it on in the evening)
I suspect we need 2 plugins, one for syntax the other one for transform.

**Comment by claudepache** [comment]
@nhz-io 

> Yep, it will be great, also pick a name too, i am not good with names, 

For the name of the repo, no need to have something imaginative, e.g. babel-optional-chaining

> and maybe even make a repo and add me as collaborator. I will get to it this weekend (Too busy at work to take it on in the evening)

For the repo, you can just create it under your own workspace, since you'll be the main author; I will eventually add a link to it.

I'm not sure I'll be able to write down the expansion of optional chaining in JS for this weekend, as I intended. In any case, I suggest that you wait I've done it before starting.

**Comment by davidyaha** [comment]
Hey @claudepache @nhz-io,
I've done things a bit backwards and went ahead to write naive implementation of a babel plugin.
https://github.com/davidyaha/ecmascript-optionals-proposal

Sorry for not contacting sooner I just done poor research on this matter before I jumped into writing code. Anyhow, The current implementation does not relay on the new syntax because it requires a fork of babylon. So the current version just changes the MemberExpression into a safer version.
Also, it does not handle deeper than one level deep objects because I've stopped there after getting to know the process of ecmascript proposals better.

Would love to join forces and create a real working implementation and start using it for some less important code bases.

This way we could maybe get more traction to get that syntax going.

Thanks for this very thorough proposal @claudepache!

**Comment by davidyaha** [comment]
@claudepache Any news on this? would love to collaborate for this operator to exist.

**Comment by claudepache** [comment]
@davidyaha Sorry for the delay, I was quite submerged by other concerns the last two weeks. I'll have more time in my disposal in a few days, so that I'll be able to write the expansion of optional chaining in JS as previously promised.

**Comment by davidyaha** [comment]
Hey @claudepache,
Thanks for answering this as well. 
Please take a look at my suggestion on #2.
Also, before you move on to write the expansion LMK what you think of the following implementation here:  https://github.com/davidyaha/ecmascript-optionals-proposal/tree/master/babel-optional-member-expression

Thanks ahead!

**Comment by tizmagik** [comment]
What's the latest here? I'd be interested in lending a hand on a babel plugin, just point me in the right direction! 😄

**Comment by chicoxyzzy** [comment]
https://github.com/babel/babel/pull/5813
