### ISSUE TITLE
Write justification for choices in syntax and semantics

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-optional-chaining#8]
As there are different opinions, we should write down justification for the editor’s choices.

Syntax:
- [x] syntax: `?.` over `.?`, etc.

Semantics:
- [ ] long short-circuiting: `a?.b.c` evaluates to `undefined` if `a` evaluates to undefined/null
- [x] no deep short-circuiting: `a?.b.c`, evaluates to the same as `a.b.c`, thus throws a TypeError, if `a.b` evaluates to undefined/null, see [es-discuss](https://esdiscuss.org/topic/optional-chaining-aka-existential-operator-null-propagation#content-12)
- [ ] `null?.b` evaluates to `undefined`, not `null`, see #12

**Comment by a-x-** [comment]
I suggest `?.`

Semantic: Question. Is it really accessible? Ok, go, get value!

---

I also use punctuation sign in texts?:
`here long code snippet for the question. it's not convenient use ? at the end`

(it is `quest-colon` as i name it: )

**Comment by a-x-** [comment]
👍 for **no deep short-circuiting**

It would be intuitively unexpected otherwise

If a === null: a?.b.c === undefined

If a?.b === null: a?.b.c // throws exception

If a?.b === null: a?.b?.c === undefined

If a === 0: a?.b.c === undefined

If a === '': a?.b.c === undefined

If a in not defined: a?.b.c // throws exception

If a === undefined but defined: a?.b.c === undefined

window?.navigator?.toString()
- browser: "[object Navigator]"
- node: ReferenceError: window is not defined

**Comment by a-x-** [comment]
We still have the issue in the strict mode.

how is it in your opinion?:
`?.window?.navigator?.toString() === undefined` (node)

**Comment by a-x-** [comment]
I updated my comments

**Comment by a-x-** [comment]
I like it for the full existial chain case:
`.?(a.b.c) // equals with typeof a !== 'undefined' && a.b && a.b.c`

I use `.?` here too because `?:`

**Comment by a-x-** [comment]
oh, I see: `x?.3:0`
`x ?. (3) : 0` or `x ? (.3) : 0`

since this moment `.?` is the more preferred solution as I see

**Comment by claudepache** [comment]
@a-x- Note that all the current choices was already pondered and have some justifications in my head. I have opened this issue mainly in order to remind me to transfer my thoughts from head to computer.

> I suggest `?.`

It is what is currently specced (with a simple lookahead in the lexical grammar order to resolve the case `x?.3:0`).

**Comment by nhz-io** [comment]
Ok, before going any further lets clarify something.
I was using coffee script heavily up until ES6 came out.
So, one of the things that i really miss is coffeescript existential operator.
Check out http://coffeescript.org/#operators and scroll down a bit to existential.
Additional feature of it that we have not discussed is an ability to invoke function if they are defined, aka: `foo?()` i would like pretty much to have that.

So, by following coffee existential operator, the expression like: `x?.3` is invalid because it has no meaning.
(so `x?.3:0` can be treated only as ternary and no other valid options are available)
Your thoughts?

**Comment by claudepache** [comment]
@nhz-io If you look at the README of this repository, there is already `foo?.()`.

To everyone:
- Don’t forget to check what is currently included in the proposal.
- Again, that issue was not intended to receive suggestions, but primarily as a personal reminder.

**Comment by osi-oswald** [comment]
Given `a` evaluates to `undefined`/`null`, why should `a?.b` always evaluate to `undefined`? Isn't this **lost information**? 

If `a?.b` always evaluates to `undefined`, I lose the information whether `a` was `undefined` or `null`. Why can't the expression return either `undefined` or `null` (depending on `a`)?

Without information loss, it is up to the consumer to decide whether he cares or not:
`if (a?.b == null) { .. }` -> As a consumer, I don't care if it evaluates to `undefined` or `null`
`if (a?.b === null) { .. }` -> As a consumer, I care if it evaluates to `null`
`if (a?.b === undefined) { .. }` -> As a consumer, I care if it evaluates to `undefined`

**Comment by claudepache** [comment]
@osi-oswald Neither `a.b` nor `a?.b` is intended to preserve arbitrary information on the base object `a`, but only to give information about the property `"b"` of that object. If a property `"b"` is absent from `a`, this is reflected by `a.b === undefined`.

In the particular case, `null` and `undefined` are both treated as immutable ”objects” with no properties. Therefore, we have `a?.b === undefined` for both `a === null` and `a === undefined`, because the property `"b"` is absent from both `null` and `undefined`.

This is not lost information, but different information.  In your second example:
`if (a?.b.c === null) { .. }` → I know that `a.b` has a `"c"` property with value `null`

**Comment by osi-oswald** [comment]
OK I see now. I was confused because I always thought `a?.b` will be syntactic sugar for `a && a.b` (as described in the **Motivation** section). But apparently it has its own meaning :sweat_smile:

**Comment by claudepache** [comment]
Remaining points are addressed in the FAQ of the official repo.
